project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "MUSA 550 Final Project"
  site-url: "https://Chling77.github.io/MUSA550_Quarto" 
  repo-url: https://github.com/Chling77/MUSA550_Quarto 
  repo-actions: [source]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-Nick Hand, 2023"

  sidebar:
    logo: "images/course-icon.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://nickhand.dev
        text: "Personal Website"
      - icon: github
        href: https://github.com/MUSA-550-Fall-2023/
        text: "MUSA 550 GitHub"
      - icon: twitter
        href: https://twitter.com/nicholashand
        text: "Nick Hand Twitter"         

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/1-HK-Topography.ipynb 
          - analysis/2-Final-Project-Explore.ipynb
          - analysis/3-Building.ipynb
          - analysis/4-Pop-Road-Zoning.ipynb
          - analysis/5-HK-Temp-NDVI.ipynb

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




